/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffb2b9",
        "on-tertiary": "#6a0934",
        "primary-container": "#ae8dff",
        "tertiary": "#ff97b5",
        "on-secondary": "#004b58",
        "primary-dim": "#8455ef",
        "secondary-dim": "#40ceed",
        "outline-variant": "#40485d",
        "on-primary-fixed-variant": "#370086",
        "on-surface": "#dee5ff",
        "secondary": "#53ddfc",
        "tertiary-dim": "#f0779d",
        "surface-container-high": "#141f38",
        "on-primary-fixed": "#000000",
        "on-secondary-container": "#ecfaff",
        "primary-fixed-dim": "#a27cff",
        "secondary-container": "#00687a",
        "surface-container-highest": "#192540",
        "primary": "#ba9eff",
        "surface-dim": "#060e20",
        "inverse-primary": "#6e3bd7",
        "error-dim": "#d73357",
        "surface": "#060e20",
        "error": "#ff6e84",
        "primary-fixed": "#ae8dff",
        "secondary-fixed-dim": "#48d4f3",
        "surface-container-lowest": "#000000",
        "tertiary-fixed-dim": "#f67ca3",
        "on-tertiary-fixed-variant": "#701039",
        "inverse-surface": "#faf8ff",
        "surface-container-low": "#091328",
        "surface-tint": "#ba9eff",
        "surface-bright": "#1f2b49",
        "on-primary-container": "#2b006e",
        "surface-container": "#0f1930",
        "secondary-fixed": "#65e1ff",
        "inverse-on-surface": "#4d556b",
        "tertiary-container": "#fd81a8",
        "error-container": "#a70138",
        "on-primary": "#39008c",
        "on-surface-variant": "#a3aac4",
        "surface-variant": "#192540",
        "on-error": "#490013",
        "on-background": "#dee5ff",
        "on-tertiary-container": "#59002a",
        "background": "#060e20",
        "on-secondary-fixed": "#003a45",
        "on-secondary-fixed-variant": "#005969",
        "tertiary-fixed": "#ff8eb0",
        "on-tertiary-fixed": "#380018",
        "outline": "#6d758c"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      }
    },
  },
  plugins: [],
}
