/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffb2b9",
        "on-tertiary": "#6a010c",
        "primary-container": "#4a0002",
        "tertiary": "#ffb1c1",
        "on-secondary": "#690005",
        "primary-dim": "#cc0000",
        "secondary-dim": "#ffb4ab",
        "outline-variant": "#333333",
        "on-primary-fixed-variant": "#4a0002",
        "on-surface": "#f2f2f2",
        "secondary": "#ff3131",
        "tertiary-dim": "#e04a5e",
        "surface-container-high": "#1a1a1a",
        "on-primary-fixed": "#ffffff",
        "on-secondary-container": "#ffdad6",
        "primary-fixed-dim": "#ff897d",
        "secondary-container": "#690005",
        "surface-container-highest": "#222222",
        "primary": "#ff3131",
        "surface-dim": "#0a0a0a",
        "inverse-primary": "#ff3131",
        "error-dim": "#d73357",
        "surface": "#0a0a0a",
        "error": "#ff6e84",
        "primary-fixed": "#ffdad6",
        "secondary-fixed-dim": "#ffb4ab",
        "surface-container-lowest": "#000000",
        "tertiary-fixed-dim": "#e04a5e",
        "on-tertiary-fixed-variant": "#6a010c",
        "inverse-surface": "#f2f2f2",
        "surface-container-low": "#0d0d0d",
        "surface-tint": "#ff3131",
        "surface-bright": "#1a1a1a",
        "on-primary-container": "#ffdad6",
        "surface-container": "#121212",
        "secondary-fixed": "#ffdad6",
        "inverse-on-surface": "#121212",
        "tertiary-container": "#4a0002",
        "error-container": "#a70138",
        "on-primary": "#ffffff",
        "on-surface-variant": "#d1d1d1",
        "surface-variant": "#121212",
        "on-error": "#490013",
        "on-background": "#f2f2f2",
        "on-tertiary-container": "#ffdad6",
        "background": "#0a0a0a",
        "on-secondary-fixed": "#2b0001",
        "on-secondary-fixed-variant": "#690005",
        "tertiary-fixed": "#ffdad6",
        "on-tertiary-fixed": "#2b0001",
        "outline": "#4d4d4d"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      }
    },
  },
  plugins: [],
}
